DataManager.Ui/Controllers/DepartamentController.cs
using DataManager.BLL.Interface;
using DataManager.BOL.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DataManager.Ui.Controllers
{
    public class DepartamentController : Controller
    {
        private readonly IDepartamentServices _departamentServices;

        public DepartamentController(IDepartamentServices departamentServices)
        {
            _departamentServices = departamentServices;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var companies = await _departamentServices.GetDepartaments();
            return View(companies);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var company = await _departamentServices.GetDepartamentById(id);
            return View(company);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Departament formData)
        {
            try
            {
                var result = await _departamentServices.CreateNewDepartament(formData);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var company = await _departamentServices.GetDepartamentById(id);

                if (company == null)
                {
                    return NotFound();
                }

                return View(company);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Departament formData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _departamentServices.UpadateDepartament(formData);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return BadRequest(ModelState);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var company = await _departamentServices.GetDepartamentById(id);

                if (company == null)
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }

                return View(company);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var company = await _departamentServices.GetDepartamentById(id);

                if (company != null)
                {
                    await _departamentServices.DeleteDepartamentById(id);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }
    }
}

DataManager.Ui/Views/Departament/Create.cshtml
@model DataManager.BOL.Entity.Departament;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Departament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Departament" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" required />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" required />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Departament" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DataManager.Ui/Views/Departament/Delete.cshtml
@model DataManager.BOL.Entity.Departament

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    <br />
    <form asp-controller="Departament" asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Departament" asp-action="Index">Back to List</a>
    </form>
</div>

DataManager.Ui/Views/Departament/Details.cshtml
@model DataManager.BOL.Entity.Departament

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Departament</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<br />
<div>
    <a asp-controller="Departament" asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-controller="Departament" asp-action="Index">Back to List</a>
</div>

DataManager.Ui/Views/Departament/Edit.cshtml
@model DataManager.BOL.Entity.Departament

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Departament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Departament" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Departament" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DataManager.Ui/Views/Departament/Index.cshtml
@model IEnumerable<DataManager.BOL.Entity.Departament>

@{
    ViewData["Title"] = "Index";
}

<h1>Departament Page</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id" class="btn btn-primary">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id" class="btn btn-success">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>