DataManager.Ui/Controllers/EmployeeController.cs
using DataManager.BLL.Interface;
using DataManager.BLL.Services;
using DataManager.BOL.Common;
using DataManager.BOL.Entity;
using DataManager.BOL.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace DataManager.Ui.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeServices _employeeServices;
        private readonly ICompanyServices _companyServices;
        private readonly IDepartamentServices _departamentServices;
        private readonly IPositionServices _positionServices;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EmployeeController(IEmployeeServices employeeServices, ICompanyServices companyServices, IDepartamentServices departamentServices, IPositionServices positionServices, IWebHostEnvironment webHostEnvironment)
        {
            _employeeServices = employeeServices;
            _companyServices = companyServices;
            _positionServices = positionServices;
            _departamentServices = departamentServices;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index(EmployeeSearch obj)
        {
            var model = new EmployeeSearch();

            var employeeList = await _employeeServices.SeachEmployees(obj);
            model.employees = employeeList;

            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var company = await _employeeServices.GetEmployeeById(id);
            return View(company);
        }


        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var model = new CreateEmployeeViewModel()
            {
                companies = await _companyServices.GetCompanies(),
                departments = await _departamentServices.GetDepartaments(),
                positions = await _positionServices.GetPositions()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateEmployeeViewModel form)
        {
            try
            {
                var result = await _employeeServices.CreateNewEmployee(form);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var employee = await _employeeServices.GetEmployeeById(id);

                var model = new CreateEmployeeViewModel()
                {
                    id = employee.id,
                    FirstName = employee.FirstName,
                    LastName = employee.LastName,
                    Patronymic = employee.Patronymic,
                    Adress = employee.Adress,
                    Phone = employee.Phone,
                    BirthDate = employee.BirthDate,
                    EntryDay = employee.EntryDay,
                    Salary = employee.Salary,
                    companies = await _companyServices.GetCompanies(),
                    departments = await _departamentServices.GetDepartaments(),
                    positions = await _positionServices.GetPositions()
                };

                if (employee == null)
                {
                    return NotFound();
                }

                return View(model);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CreateEmployeeViewModel employeeView)
        {
            try
            {
                var result = await _employeeServices.UpadateEmployee(employeeView);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var company = await _employeeServices.GetEmployeeById(id);

                if (company == null)
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }

                return View(company);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var company = await _employeeServices.GetEmployeeById(id);

                if (company != null)
                {
                    await _employeeServices.DeleteEmployeeById(id);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        public async Task<FileResult> Download()
        {
            var filePath = Path.Combine(_webHostEnvironment.ContentRootPath, "Files", "file.txt");

            await _employeeServices.FielRecordingAsync(filePath);
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            string fileName = "file.txt";
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

DataManager.Ui/Controllers/PositionController.cs
using DataManager.BLL.Interface;
using DataManager.BOL.Entity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DataManager.Ui.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPositionServices _positionServices;

        public PositionController(IPositionServices positionServices)
        {
            _positionServices = positionServices;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var companies = await _positionServices.GetPositions();
            return View(companies);
        }

        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            var company = await _positionServices.GetPositionsById(id);
            return View(company);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Position formData)
        {
            try
            {
                var result = await _positionServices.CreateNewPosition(formData);

                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            try
            {
                var company = await _positionServices.GetPositionsById(id);

                if (company == null)
                {
                    return NotFound();
                }

                return View(company);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Position formData)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _positionServices.UpadatePosition(formData);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return BadRequest(ModelState);
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var company = await _positionServices.GetPositionsById(id);

                if (company == null)
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }

                return View(company);
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var company = await _positionServices.GetPositionsById(id);

                if (company != null)
                {
                    await _positionServices.DeletePositionById(id);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return NotFound($"Компанію з id={id} не знайдено.");
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex);
            }
        }
    }
}

DataManager.Ui/Views/Employee/Create.cshtml
@model DataManager.BOL.ViewModel.CreateEmployeeViewModel;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Empoloyee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Employee" asp-action="Create">
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" required />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" required />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patronymic" class="control-label"></label>
                <input asp-for="Patronymic" class="form-control"/>

            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" required />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" required />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" required />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDay" class="control-label"></label>
                <input asp-for="EntryDay" class="form-control" required />
                <span asp-validation-for="EntryDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" required />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Departament_Id" class="control-label">Departament</label>
                @Html.DropDownListFor(x => x.Departament_Id, new SelectList(Model.departments, "id", "Title"), "-- Select Departament --", new { @class = "form-control" })
                <span asp-validation-for="Departament_Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Position_Id" class="control-label">Position</label>
                @Html.DropDownListFor(x => x.Position_Id, new SelectList(Model.positions, "id", "Title"), "-- Select Position --", new { @class = "form-control" })
                <span asp-validation-for="Position_Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Company_Id" class="control-label">Company</label>
                @Html.DropDownListFor(x => x.Company_Id, new SelectList(Model.companies, "id", "Title"), "-- Select Company --", new { @class = "form-control" })
                <span asp-validation-for="Company_Id" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Employee" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DataManager.Ui/Views/Employee/Delete.cshtml
@model DataManager.BOL.Entity.Position

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Position</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    <br />
    <form asp-controller="Position" asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Position" asp-action="Index">Back to List</a>
    </form>
</div>

DataManager.Ui/Views/Employee/Details.cshtml
@model DataManager.BOL.ViewModel.EmployeeViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Patronymic)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EntryDay)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EntryDay)
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Departament)
        </dt>
        <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Departament)
        </dd>
        <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Company)
        </dd>

    </dl>
</div>
<br />
<div>
    <a asp-controller="Employee" asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-controller="Employee" asp-action="Index">Back to List</a>
</div>

DataManager.Ui/Views/Employee/Edit.cshtml
@model DataManager.BOL.ViewModel.CreateEmployeeViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Position</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Employee" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
        
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">fvrfv</label>
                <input asp-for="FirstName" class="form-control" required />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" required />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patronymic" class="control-label"></label>
                <input asp-for="Patronymic" class="form-control"/>

            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" required />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" required />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" required />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDay" class="control-label"></label>
                <input asp-for="EntryDay" class="form-control" required />
                <span asp-validation-for="EntryDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" required />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Departament_Id" class="control-label">Departament</label>
                @Html.DropDownListFor(x => x.Departament_Id, new SelectList(Model.departments, "id", "Title"), "-- Select Departament --", new { @class = "form-control" })
                <span asp-validation-for="Departament_Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Position_Id" class="control-label">Position</label>
                @Html.DropDownListFor(x => x.Position_Id, new SelectList(Model.positions, "id", "Title"), "-- Select Position --", new { @class = "form-control" })
                <span asp-validation-for="Position_Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Company_Id" class="control-label">Company</label>
                @Html.DropDownListFor(x => x.Company_Id, new SelectList(Model.companies, "id", "Title"), "-- Select Company --", new { @class = "form-control" })
                <span asp-validation-for="Company_Id" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Employee" asp-action="Index">Back to List</a>
</div>

DataManager.Ui/Views/Employee/Index.cshtml
@model DataManager.BOL.Common.EmployeeSearch

@{
    ViewData["Title"] = "Index";
}

<h1>Employee Search Page</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>

<form asp-controller="Employee" asp-action="Index" method="get">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="FistName" class="control-label"></label>
        <input asp-for="FistName" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label"></label>
        <input asp-for="LastName" class="form-control"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>FirstName</th>
            <th>LastName</th>
            <th>Patronymic</th>
            <th>Adress</th>
            <th>Phone</th>
            <th>BirthDate</th>
            <th>EntryDay</th>
            <th>Salary</th>
            <th>Departament</th>
            <th>Position</th>
            <th>Company</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model.employees != null)
        {
            @foreach (var item in Model.employees)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Patronymic)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Adress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EntryDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Salary)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Departament)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Company)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.id" class="btn btn-primary" style="width: 70px">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.id" class="btn btn-success" style="width: 70px;">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.id" class="btn btn-danger" style="width: 70px">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<p><a asp-action="Download" class="btn btn-primary" style="width: 150px">Download txt</a></p>